### PR TITLE
Make the copy button nicer using an SVG icon

### PR DESCRIPTION
**Pull request by Cito**
I like this plugin, but I find the copy button a bit obtrusive. This PR replaces the button with a nicer and more lightweight copy icon.

### CODE REVIEW

**Comment by Fastidious** [comment]
I got your forked version, and tried installing it to no avail. It fails to load. It is compatible with `0.10.13`?

**Comment by Cito** [comment]
I'm currently using it with 0.11.0 and never had problems with it.

**Comment by Fastidious** [comment]
Hmm, will give it another try. Will remove the official one, download the zip from your repo, expand and move the plugin directory to the plugins directory, and see how it goes.

**Comment by Fastidious** [comment]
Worked perfectly, thanks! I was missing the actual building process.

**Comment by MartynKeigher** [comment]
Is this ever going to get merged??

Also, given that this repo has no 'Issues' board... is it possible to also request that the COPY button only shows for a code block, for only when I hover over the code block??

**Review by natpalmer-e4o4 — APPROVED** [review]
Sorry for the delay, had notifications disabled :\

**Pull request merged**
